spring.application.name=demo1
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.username=memgraph
spring.neo4j.password=
spring.jpa.hibernate.ddl-auto=update

gemini.api.key=${GEMINI_API_KEY:placeholder}
openai.api.key=${OPENAI_API_KEY:placeholder}

adzuna.api.id=${ADZUNA_APP_ID:ef9d97f4}
adzuna.api.key=${ADZUNA_APP_KEY:}

jsearch.api.key=${JSEARCH_API_KEY:}
jooble.api.key=${JOBBLE_API_KEY:}